
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dashboard   # Имя базы
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./back
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dashboard  # подключение к базе dashboard

  frontend:
    build: ./front
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000   # фронт будет обращаться к бэку через localhost

volumes:
  db_data:
